config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/index'

  resources :c_attributes

  resources :options

  resources :choice_rows

  resources :choice_sets

  resources :choices

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'staticpages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/c_attribute.rb
class CAttribute < ActiveRecord::Base
  belongs_to :choice_set
  has_many :choices
end

app/controllers/c_attributes_controller.rb
class CAttributesController < ApplicationController
  before_action :set_c_attribute, only: [:show, :edit, :update, :destroy]

  # GET /c_attributes
  # GET /c_attributes.json
  def index
    @c_attributes = CAttribute.all
  end

  # GET /c_attributes/1
  # GET /c_attributes/1.json
  def show
  end

  # GET /c_attributes/new
  def new
    @c_attribute = CAttribute.new
  end

  # GET /c_attributes/1/edit
  def edit
  end

  # POST /c_attributes
  # POST /c_attributes.json
  def create
    @c_attribute = CAttribute.new(c_attribute_params)

    respond_to do |format|
      if @c_attribute.save
        format.html { redirect_to @c_attribute, notice: 'C attribute was successfully created.' }
        format.json { render :show, status: :created, location: @c_attribute }
      else
        format.html { render :new }
        format.json { render json: @c_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /c_attributes/1
  # PATCH/PUT /c_attributes/1.json
  def update
    respond_to do |format|
      if @c_attribute.update(c_attribute_params)
        format.html { redirect_to @c_attribute, notice: 'C attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @c_attribute }
      else
        format.html { render :edit }
        format.json { render json: @c_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /c_attributes/1
  # DELETE /c_attributes/1.json
  def destroy
    @c_attribute.destroy
    respond_to do |format|
      format.html { redirect_to c_attributes_url, notice: 'C attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_c_attribute
      @c_attribute = CAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def c_attribute_params
      params.require(:c_attribute).permit(:display_order, :choice_set_id, :name, :description)
    end
end

app/helpers/c_attributes_helper.rb
module CAttributesHelper
end

app/views/c_attributes/_form.html.erb
<%= form_for @c_attribute, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :display_order, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :display_order, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  c_attributes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/c_attributes/edit.html.erb
<%- model_class = CAttribute -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => CAttribute %></h1>
</div>
<%= render :partial => 'form' %>

app/views/c_attributes/index.html.erb
<%- model_class = CAttribute -%>
<div class="page-header">
  <h1><%=t '.title', :default => CAttribute %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:display_order) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @c_attributes.each do |c_attribute| %>
      <tr>
        <td><%= c_attribute.id %></td>
        <td><%= c_attribute.display_order %></td>
        <td><%= c_attribute.name %></td>
        <td><%= c_attribute.description %></td>
        <td><%=l c_attribute.created_at, format: :long %></td>
        <td>
          <%= link_to c_attribute_path(c_attribute), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to c_attribute_path(c_attribute), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_c_attribute_path,
            :class => 'btn btn-primary' %>

app/views/c_attributes/new.html.erb
<%- model_class = CAttribute -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => CAttribute %></h1>
</div>
<%= render :partial => 'form' %>

app/views/c_attributes/show.html.erb
<%- model_class = CAttribute -%>
<div class="page-header">
  <h1><%=t '.title', :default => CAttribute %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:display_order) %></dt>
      <dd><pre class="prettyprint"><%= @c_attribute.display_order %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @c_attribute.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @c_attribute.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              c_attributes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_c_attribute_path(@c_attribute), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              c_attribute_path(@c_attribute),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>