config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/index'

  resources :c_attributes

  resources :options

  resources :choice_rows

  resources :choice_sets

  resources :choices

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'staticpages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/choice_row.rb
class ChoiceRow < ActiveRecord::Base
  belongs_to :choice_set
  has_many :choices
end

app/controllers/choice_rows_controller.rb
class ChoiceRowsController < ApplicationController
  before_action :set_choice_row, only: [:show, :edit, :update, :destroy]

  # GET /choice_rows
  # GET /choice_rows.json
  def index
    @choice_rows = ChoiceRow.all
  end

  # GET /choice_rows/1
  # GET /choice_rows/1.json
  def show
  end

  # GET /choice_rows/new
  def new
    @choice_row = ChoiceRow.new
  end

  # GET /choice_rows/1/edit
  def edit
  end

  # POST /choice_rows
  # POST /choice_rows.json
  def create
    @choice_row = ChoiceRow.new(choice_row_params)

    respond_to do |format|
      if @choice_row.save
        format.html { redirect_to @choice_row, notice: 'Choice row was successfully created.' }
        format.json { render :show, status: :created, location: @choice_row }
      else
        format.html { render :new }
        format.json { render json: @choice_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choice_rows/1
  # PATCH/PUT /choice_rows/1.json
  def update
    respond_to do |format|
      if @choice_row.update(choice_row_params)
        format.html { redirect_to @choice_row, notice: 'Choice row was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice_row }
      else
        format.html { render :edit }
        format.json { render json: @choice_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choice_rows/1
  # DELETE /choice_rows/1.json
  def destroy
    @choice_row.destroy
    respond_to do |format|
      format.html { redirect_to choice_rows_url, notice: 'Choice row was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice_row
      @choice_row = ChoiceRow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_row_params
      params.require(:choice_row).permit(:choice_set_id, :display_order)
    end
end

app/helpers/choice_rows_helper.rb
module ChoiceRowsHelper
end

app/views/choice_rows/_form.html.erb
<%= form_for @choice_row, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :display_order, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :display_order, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  choice_rows_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/choice_rows/edit.html.erb
<%- model_class = ChoiceRow -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ChoiceRow %></h1>
</div>
<%= render :partial => 'form' %>

app/views/choice_rows/index.html.erb
<%- model_class = ChoiceRow -%>
<div class="page-header">
  <h1><%=t '.title', :default => ChoiceRow %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:display_order) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @choice_rows.each do |choice_row| %>
      <tr>
        <td><%= choice_row.id %></td>
        <td><%= choice_row.display_order %></td>
        <td><%=l choice_row.created_at, format: :long %></td>
        <td>
          <%= link_to choice_row_path(choice_row), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to choice_row_path(choice_row), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_choice_row_path,
            :class => 'btn btn-primary' %>

app/views/choice_rows/new.html.erb
<%- model_class = ChoiceRow -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ChoiceRow %></h1>
</div>
<%= render :partial => 'form' %>

app/views/choice_rows/show.html.erb
<%- model_class = ChoiceRow -%>
<div class="page-header">
  <h1><%=t '.title', :default => ChoiceRow %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:display_order) %></dt>
      <dd><pre class="prettyprint"><%= @choice_row.display_order %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              choice_rows_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_choice_row_path(@choice_row), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              choice_row_path(@choice_row),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>